use_frameworks!

platform :ios, '10.0'

target 'TCocoapodsLibrary_Example' do
  pod 'TCocoapodsLibrary', :path => '../'

  target 'TCocoapodsLibrary_Tests' do
    inherit! :search_paths

    
  end
end
